### ISSUE TITLE
Planning a community event in March/April

### ISSUE THREAD

**Issue by gurumukhi** [webvr-india/activities#16]
Lets have a major community event in march/april in which we can involve all active members from different cities of India. We all can join online on the night and work \ discuss \ plan \ have fun 😊 

Putting initial plan on https://public.etherpad-mozilla.org/p/AFrameHackNightIndia. Once we have a solid plan, we will put it here and then roll out to larger community.

**Comment by DineshMv** [comment]
Suggested my thoughts. i.e., Web-VR community structure (draft) which helps to guide and curate the newbies.

**Comment by gurumukhi** [comment]
Event conducted successfully, thanks all. closing this issue :-)
