### ISSUE TITLE
A-Frame bugs |  good-first-bugs for beginners | Contest Proposal

### ISSUE THREAD

**Issue by shahbaz17** [webvr-india/activities#17]
With the new good first bug of A-frame , I am thinking of a contest for our WebVR India Community members where they will follow the below guidelines . 
I would like to get other members views on this, You liked the idea? Have any improvements to suggest? kindly comment here about this.

Did You Know? - A-Frame bugs are filed on github (not on bugzilla as most of legacy products of mozilla), and you can pick one and fix. If you are looking for good-first-bugs, they are marked with “help wanted (easy)” tag which can be found on this link - [https://github.com/aframevr/aframe/issues?q=is:issue+is:open+label:"help+wanted+(easy)"](https://github.com/aframevr/aframe/issues?q=is:issue+is:open+label:"help+wanted+(easy)")

With these good first bugs, we are introducing a new competition - **WebVR Hack Star**

**How to get involved in this ?**

- Visit the above link and comment on the issue which you would like to work on - '**I want to work on this**'

- Ask for help if you need, since these bugs are for absolute beginners you will be able to fix it pretty fast [ don't worry you will get enough help from a-frame team and WebVR-India team ]

- Once you have fixed the issue, you will be able to report it to the community using a new issue which we will create under volunteer-contributions.

**What you will get ?**

- Top 3 members will get Sony Xperia Z3C to hack and explore, who have fixed maximum number of bugs. We will request the phones using [this campaign](https://discourse.mozilla-community.org/t/sony-z3c-devices-to-support-communities-and-mozillians/15032/5)

- Remaining member will get a special T-shirt from WebVR India who have fixed minimum 3 bugs.

**Future Scope of this contest ?**

- While fixing bugs you will get to know about the codebase of A-frame, which enables you to a good developer and an asset to this project.

- You will be able to fix lot more bugs of a-frame

- And eventually becomes a **WebVR Hack Star**, who can guide others to become like them.

**Comment by gurumukhi** [comment]
I am logging request for mobile phones, @shahbaz17 kindly initiate discussion about t shirt design.

**Comment by shahbaz17** [comment]
Sure. I'll share the initial design on superstar group by tonight.

**Comment by gurumukhi** [comment]
Hi @ngokevin, do you have any suggestions for this contest? During this contest many new developers will be getting started with bugs fixing, let us know if you have any resources or documentation which can help them.

**Comment by ngokevin** [comment]
There's https://github.com/aframevr/aframe/issues?q=is:issue+is:open+label:%22help+wanted+(easy)%22

and

https://github.com/aframevr/aframe/blob/master/CONTRIBUTING.md

**Comment by gurumukhi** [comment]
Can someone take care of logging phone's request, I couldn't do it yet as i was busy with other projects. We also need to launch this contest by making announcement  about this contest to wider audience. @shahbaz17 @lavish205 @Srushtika @tushararora @shubhamgeete @vibhanshu @akshit13 can take this forward?

**Comment by shahbaz17** [comment]
I will be logging the device request on behalf on webvr-india and we are starting this contest very soon.

**Comment by gurumukhi** [comment]
Successfully conducted the contest (https://github.com/webvr-india/volunteer-contributions/issues/33). Thanks all :-) Closing this issue.
