### ISSUE TITLE
Create github.io website

### ISSUE THREAD

**Issue by gurumukhi** [webvr-india/activities#8]
webvr-india.github.io website with -

* About us
** Volunteers names 
** Volunteers projects/scenes (replacement of wiki page)
** Events Conducted
** Blogposts etc

* Resources
** A-Frame examples
** Useful links

* Activities 
** Meeting notes
** Contests info

**Comment by abhi12ravi** [comment]
I'm interested to work on this site. Will we be using an existing theme or build from scratch?

**Comment by mukeshpathak345** [comment]
About us
** Volunteers names: Mukesh Pathak Mike
** Events Conducted: 20 January 2017
** Blogposts link:  https://mikebhopal.wordpress.com/2017/01/23/mozvr-camp-iet-davv-indore/

**Comment by gurumukhi** [comment]
@abhi12ravi anything should be fine! @tushararora what do you say?

@mukeshpathak345 please update your contributions at http://github.com/webvr-india/volunteer-contributions/issues

**Comment by tushararora** [comment]
I would suggest creating a website from scratch. Of course it'll take more time than usual but at the same time will give volunteers an opportunity to come up with new ideas, learn web technologies, learn PR based workflow, filing bugs and lots of other skills that might be useful for diving into other mozilla projects.

If it has to be done as early as possible, I would suggest a static site generator like Jekyll with a multitude of themes and great support for gh-pages.

**Comment by gurumukhi** [comment]
Maintenance is also important factor here. We have to make sure that updating content on website is super easy, as we are never sure how much time volunteers would have in future whenever we need to make changes.

**Comment by gurumukhi** [comment]
Any update here! Let this get rolling soon 👍

**Comment by gurumukhi** [comment]
Lets take this discussion forward to https://github.com/webvr-india/webvr-india.github.io/issues/22.

@abhi12ravi @mukeshpathak345 you guys are more than welcome to contribute to the website which on which we have already started working from the last Hack Night event.
