### ISSUE TITLE
Prepare 'A-Frame Cheat Sheet'

### ISSUE THREAD

**Issue by gurumukhi** [webvr-india/activities#9]
Like Rust cheat sheet, need to prepare a-aframe cheat sheet.

**Comment by shahbaz17** [comment]
How does Rust Cheat Sheet looks like ? Any reference

**Comment by Srushtika** [comment]
Attached reference!

**Comment by gurumukhi** [comment]
@Srushtika did an amazing job to come up with this design, Thanks a lot Srushtika.

![front](https://cloud.githubusercontent.com/assets/2748973/22174859/a17d59e2-e00e-11e6-9bfe-6a2a7ad88620.jpg)

![back](https://cloud.githubusercontent.com/assets/2748973/22174862/aecb76ba-e00e-11e6-93a0-f98c5b95e631.jpg)

Hi All, Feel free to add your feedback on this design ..

**Comment by gurumukhi** [comment]
I will contact @ngokevin about helping us in getting thess card in MozActivate swags ( https://wiki.mozilla.org/India/MozActivate#Swag_Pack: )

**Comment by Srushtika** [comment]
![collage](https://cloud.githubusercontent.com/assets/5900152/22184143/24037a7a-e0f2-11e6-843c-fea4d03c5cde.jpg)
![back](https://cloud.githubusercontent.com/assets/5900152/22184144/250e0b88-e0f2-11e6-95ea-d83d29853652.jpg)
HD jpg files.

**Comment by Srushtika** [comment]
![back](https://cloud.githubusercontent.com/assets/5900152/22184158/3baec256-e0f2-11e6-8284-ad79bdf3e8c8.jpg)
![front](https://cloud.githubusercontent.com/assets/5900152/22184160/3d844f42-e0f2-11e6-9664-ae85a8edce0f.jpg)
HD jpg files

**Comment by gurumukhi** [comment]
FTR this is rust sheet. Back side of this is just a Mozilla logo in Reddish background (with whatcanidoformozilla link i think)..

![rust1](https://cloud.githubusercontent.com/assets/2748973/22616786/51dcdc74-eada-11e6-8f50-2c254b543667.jpeg)

**Comment by gurumukhi** [comment]
Closing this issue as we are done with the awesome design of cheat-sheet :-)
